name: Docker Image CI

on:
  push:
    branches: [ "master", "develop","feature_regressiontests"]
  pull_request:
    branches: [ "master", "develop","feature_regressiontests"]

jobs:
  run_regression:
      name: Run tests in ghcr container
      runs-on: ubuntu-latest
      steps:
        - name: Pre Cleanup
          uses: docker://ghcr.io/evertbunschoten/pp_template_regression:latest
          with:
            entrypoint: /bin/rm
            args: -rf src/
        
        - name: Run regression tests
          uses: docker://ghcr.io/evertbunschoten/pp_template_regression:latest
          with:
            args: -b ${{ github.ref }} -s run_regression.py
